
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module cooling(

	//////////// ADC //////////
	output		          		ADC_CONVST,
	output		          		ADC_SCK,
	output		          		ADC_SDI,
	input 		          		ADC_SDO,

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// GPIO_0, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);

wire [11:0] analog [7:0];

adc_control adc0(
	.CLOCK		(FPGA_CLK1_50),    //                clk.clk
	.ADC_SCLK	(ADC_SCK), // external_interface.SCLK
	.ADC_CS_N	(ADC_CONVST), //                   .CS_N
	.ADC_DOUT	(ADC_SDO), //                   .DOUT
	.ADC_DIN		(ADC_SDI),  //                   .DIN
	.CH0			(analog[0]),      //           readings.CH0
	.CH1			(analog[1]),      //                   .CH1
	.CH2			(analog[2]),      //                   .CH2
	.CH3			(analog[3]),      //                   .CH3
	.CH4			(analog[4]),      //                   .CH4
	.CH5			(analog[5]),      //                   .CH5
	.CH6			(analog[6]),      //                   .CH6
	.CH7			(analog[7]),      //                   .CH7
	.RESET		(!KEY[0])     //              reset.reset
	);

	
cooling_system cs1(
	.min_temp(30),
	.max_temp(60),
	.cur_temp(analog[0]),
	
	.fan_control(GPIO[0]),
	);


endmodule
